name: CI/CD Pipeline

on:
  # Trigger on pushes to the main and dev branch
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./backend.dockerfile
        push: true
        tags: libwebservicesmu/chatbot-app-backend:latest

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/frontend.dockerfile
        push: true
        tags: libwebservicesmu/chatbot-app-frontend:latest
